apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-task-pvc
spec:
  volumeName: my-task-pvc
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
