apiVersion: v1
kind: Pod
metadata:
  name: lakshman-pod-with-pvc
  labels:
    name: lakshman-pod-with-pvc
spec:
  containers:
  - name: lakshman-pod-with-pvc
    image: **********/kubernetes:**************
    ports:
      - containerPort: 8080
        name: www
    volumeMounts:
      - name: www-persistent-storage
        mountPath: /home/lakshman/storage
  volumes:
    - name: www-persistent-storage
      persistentVolumeClaim:
        claimName: my-task-pvc
